services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 4433:443
    
    environment:
      - TZ=${TIME_ZONE}
      - PGID=1000
      - PUID=1000

    env_file:
      - '.env'
    
    volumes:
      - ${CLOUD_PATH}/data:/data
      - ${CLOUD_PATH}/config:/config
