services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 4433:443
    
    environment:
      - TZ=IND
      - PGID=1000
      - PUID=1000
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost,${TRUSTED_DOMAINS} # comma-separated list

    env_file:
      - 'nc.env'
    
    volumes:
      - ${CLOUD_PATH}/data:/data
      - ${CLOUD_PATH}/config:/config
