services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${ARRPATH}/config/prowlarr:/config
      - ${ARRPATH}/backup/prowlarr:/data/Backup
      - ${ARRPATH}/downloads:/downloads
    ports:
      - 6241:9696
    restart: unless-stopped
    env_file:
      - 'arr.env'

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${ARRPATH}/config/sonarr:/config
      - ${ARRPATH}/backup/sonarr:/data/Backup
      - ${ARRPATH}/shows:/data/tvshows
      - ${ARRPATH}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    env_file:
      - 'arr.env'

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - ${ARRPATH}/config/radarr:/config
      - ${ARRPATH}/movies:/data/movies
      - ${ARRPATH}/backup/radarr:/data/Backup
      - ${ARRPATH}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    env_file:
      - 'arr.env'

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${ARRPATH}/config/lidarr:/config
      - ${ARRPATH}/music:/data/musicfolder
      - ${ARRPATH}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    env_file:
      - 'arr.env'

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    volumes:
      - ${ARRPATH}/config/readarr:/config
      - ${ARRPATH}/books:/data/books
      - ${ARRPATH}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    env_file:
      - 'arr.env'

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${ARRPATH}/configs/homarr:/app/data/configs
      - ${ARRPATH}/icons/homarr:/app/public/icons
      - ${ARRPATH}/data/homarr:/data
    ports:
      - '7575:7575'
    env_file:
      - 'arr.env'

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${ARRPATH}/config/qbittorrent:/config
      - ${ARRPATH}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    healthcheck:
      start_period: 15s
    env_file:
      - 'arr.env'