services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    
    volumes:
      - ${JELLY_PATH}/config:/config
      - ${ARRPATH}/movies:/data/Movies
      - ${ARRPATH}/tvshows:/data/TVShows
      - ${ARRPATH}/music:/data/Music
      - ${ARRPATH}/books:/data/Books
    
    env_file:
      - 'jelly.env'
    
    restart: unless-stopped
