name: bentopdf

services:
  bentopdf-ui:
    image: ghcr.io/tashifkhan/bentopdf-ui:sha-e29f380@sha256:0ef562afa9412077f908cb6938e806aa381e0667752aad3a38e73d9997c35d7a
    container_name: bentopdf-ui
    hostname: bentopdf-ui
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=64m,mode=1777
    networks:
      nginx-proxy-manager:
        aliases:
          - bentopdf-ui
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: 100
    mem_limit: 384m
    cpus: 0.50
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  nginx-proxy-manager:
    name: nginx-proxy-manager_nginxproxyman
    external: true
