name: bentopdf

services:
  bentopdf-ui:
    image: ghcr.io/tashifkhan/bentopdf-ui:sha-30463b7@sha256:ed3350aed1a15835c8e9f376fa0ba02066c4c9dc2f37d6e87ebe121a543dc434
    container_name: bentopdf-ui
    hostname: bentopdf-ui
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=64m,mode=1777
    networks:
      nginx-proxy-manager:
        aliases:
          - bentopdf-ui
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: 100
    mem_limit: 384m
    cpus: 0.50
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  nginx-proxy-manager:
    name: nginx-proxy-manager_nginxproxyman
    external: true
