services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    platform: linux/amd64
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${ARR_PATH}/config/prowlarr:/config
      - ${ARR_PATH}/backup/prowlarr:/data/Backup
      - ${ARR_PATH}/downloads:/downloads
    ports:
      - 4204:9696
    restart: unless-stopped
    env_file:
      - '.env'

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    platform: linux/amd64
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${ARR_PATH}/config/sonarr:/config
      - ${ARR_PATH}/backup/sonarr:/data/Backup
      - ${ARR_PATH}/shows:/data/tvshows
      - ${ARR_PATH}/downloads:/downloads
    ports:
      - 4205:8989
    restart: unless-stopped
    env_file:
      - '.env'

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    platform: linux/amd64
    container_name: radarr
    hostname: radarr
    volumes:
      - ${ARR_PATH}/config/radarr:/config
      - ${ARR_PATH}/movies:/data/movies
      - ${ARR_PATH}/backup/radarr:/data/Backup
      - ${ARR_PATH}/downloads:/downloads
    ports:
      - 4206:7878
    restart: unless-stopped
    env_file:
      - '.env'

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    platform: linux/amd64
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${ARR_PATH}/config/lidarr:/config
      - ${ARR_PATH}/music:/data/musicfolder
      - ${ARR_PATH}/downloads:/downloads
    ports:
      - 4207:8686
    restart: unless-stopped
    env_file:
      - '.env'

  readarr:
    image: hotio/readarr:latest
    container_name: readarr
    hostname: readarr
    volumes:
      - ${ARR_PATH}/config/readarr:/config
      - ${ARR_PATH}/books:/data/books
      - ${ARR_PATH}/downloads:/downloads
    ports:
      - 4208:8787
    restart: unless-stopped
    env_file:
      - '.env'

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - ${ARR_PATH}/configs/homarr:/app/data/configs
      - ${ARR_PATH}/icons/homarr:/app/public/icons
      - ${ARR_PATH}/data/homarr:/data
    ports:
      - '4209:7575'
    env_file:
      - '.env'

  qbittorrent:
    image: hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${ARR_PATH}/config/qbittorrent:/config
      - ${ARR_PATH}/downloads:/downloads
    ports:
      - 4203:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

    healthcheck:
      start_period: 15s

    env_file:
      - '.env'
