services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    
    ports:
      - '4201:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    
    volumes:
      - ${JELLY_PATH}/config:/config
      - ${ARR_PATH}/movies:/data/Movies
      - ${ARR_PATH}/shows:/data/TVShows
      - ${ARR_PATH}/music:/data/Music
      - ${ARR_PATH}/books:/data/Books
    
    env_file:
      - '.env'
    
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    
    env_file:
      - '.env'
    
    volumes:
      - ${JELLY_PATH}/jellyseerr:/app/config
    
    ports:
      - 4202:5055

    dns:
      - 8.8.8.8
    
    restart: unless-stopped
