services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    
    volumes:
      - ${JELLY_PATH}/config:/config
      - ${ARR_PATH}/movies:/data/Movies
      - ${ARR_PATH}/tvshows:/data/TVShows
      - ${ARR_PATH}/music:/data/Music
      - ${ARR_PATH}/books:/data/Books
    
    env_file:
      - 'jelly.env'
    
    restart: unless-stopped

    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=${TIME_ZONE}
      
      volumes:
        - ${JELLY_PATH}/jellyseerr:/app/config
      
      ports:
        - 5055:5055
      
      restart: unless-stopped
