services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    hostname: searxng
    restart: unless-stopped
    ports:
      - 4212:8080
    volumes:
      - ${SEARXNG_PATH}/settings.yml:/etc/searxng/settings.yml:ro
      - ${SEARXNG_PATH}/limiter.toml:/etc/searxng/limiter.toml:ro
    environment:
      - SEARXNG_BASE_URL=https://search.taf.sh/
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - TZ=${TIME_ZONE}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    depends_on:
      - valkey
    env_file:
      - '.env'

  valkey:
    image: valkey/valkey:8-alpine
    container_name: searxng-valkey
    hostname: valkey
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - ${SEARXNG_PATH}/redis:/data
