use_default_settings: true

general:
  instance_name: "SearXNG"
  debug: false
  privacypolicy_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 15
  formats:
    - html
    - json
    - csv
    - rss

server:
  secret_key: "${SEARXNG_SECRET}"
  bind_address: "0.0.0.0"
  port: 8080
  base_url: "https://search.taf.sh/"
  image_proxy: true
  limiter: true
  public_instance: true
  method: "GET"

valkey:
  url: valkey://valkey:6379/0

ui:
  static_use_hash: true
  default_theme: simple
  default_locale: ""
  query_in_title: true
  infinite_scroll: true
  center_alignment: false
  results_on_new_tab: false
  theme_args:
    simple_style: auto

outgoing:
  request_timeout: 5
  max_request_timeout: 15
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

engines:
  - name: google
    engine: google
    shortcut: go
    inactive: true
    disabled: true

  - name: google cse
    engine: google_cse
    shortcut: g
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: w
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: arxiv
    engine: arxiv
    shortcut: ar
    disabled: false

  - name: docker hub
    engine: docker_hub
    shortcut: dh
    disabled: false

  - name: pypi
    engine: pypi
    shortcut: py
    disabled: false
